# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.cache/wt [current_project]
set_property parent.project_path /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.runs/ila_0_synth_1/ila_0.dcp
set_property used_in_implementation false [get_files /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.runs/ila_0_synth_1/ila_0.dcp]
read_mem {
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/ram.mem
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/rom.mem
}
read_verilog -library xil_defaultlib {
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/imports/new/counter.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/MouseTransmitter.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/MouseReceiver.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/MouseMasterSM.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/mux_4x1.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/MouseTransceiver.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/imports/Downloads/seg7decoder.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/imports/sources_1/new/top.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/Processor.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/Timer.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/ALU.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/RAM.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/ROM.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/Mouse_Driver.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/seg7_Driver.v
  /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/sources_1/new/LED_Driver.v
}
read_xdc /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/constrs_1/imports/new/MouseXDC.xdc
set_property used_in_implementation false [get_files /home/tommyj/AMD_FPGA/Mouse_Interface_2015/Mouse_Interface_2015.srcs/constrs_1/imports/new/MouseXDC.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
